### ISSUE TITLE
Config option to only show errors

### ISSUE THREAD

**Issue by jdillard** [documatt/sphinx-reredirects#1]
Love the extension, I've been using it more and more!

It would be nice if there was a config option to only show errors so the build log doesn't get too busy when there are lots of redirects.

**Comment by liborjelinek** [comment]
Thank you very much for kind words ❤️

But to your question. It is already possible. The extension respects Sphinx logging level during the build.

If you want to mute all the *Overwriting 'index.html' with redirect to 'https:/documatt.com/sphinx-themes/index.html'.* messages, just add `-q` (as quiet) to `sphinx-build`:

    sphinx-build -b html -q docs/ build/html

Or, to `SPHINXOPTS` in `Makefile`:

    SPHINXOPTS    ?= -q

**Comment by liborjelinek** [comment]
Hey, you are the author of sphinx-sitemap :-) In turn, the extension which I love and use everyday too!

**Comment by jdillard** [comment]
Ah good call, I didn't think about that. I was already using `-q` in CI to reduce log size and make it easier to spot warnings/errors.

Glad to hear! The work you put into Documatt is inspirational, keep it up!
